name: Release

on:
  workflow_dispatch:

jobs:
  publish-to-npm:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]
        # pnpm: [8]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: ./.github/actions/build-setup
        with:
          node-version: ${{ matrix.node }}

      - name: Build Lib
        run: pnpm build:lib

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
        run: pnpm semantic-release
